### PR TITLE
Make DPF path configurable and fix 'submodules' rule to work in freshly cloned project

### PR DESCRIPTION
**Pull request by SpotlightKid**
You can now pass `DPF_PATH` to make to set the the path to DPF library directory.

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Fixes: #18

**Comment by SpotlightKid** [comment]
@pdesaulniers What do you think about this? Does this fit your use case?

**Comment by pdesaulniers** [comment]
It looks nice! However:

1) The `MISSING_SUBMODULES_ERROR` message does not appear to be displayed anywhere
2) The dpf/Makefile.base.mk file is not included in the top-level Makefile anymore. This might cause some issues, considering that the 'installation directories' section refers to variables which are defined in dpf/Makefile.base.mk (such as `MACOS_OR_WINDOWS`): https://github.com/SpotlightKid/cookiecutter-dpf-effect/blob/c502d05e8fac8cceb5db3f316feb92486f158971/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L30-L56

**Comment by SpotlightKid** [comment]
Err, botched rebase. Hang on a minute...

**Comment by SpotlightKid** [comment]
@pdesaulniers Should be fixed now. Please check again.

**Comment by pdesaulniers** [comment]
Cool! It seems pretty great now.

I see two more (minor) things:
1) The build fails when the current path contains spaces. I believe we can fix this by quoting the DPF_PATH variable in some places, and using a wildcard to include Makefile.base.mk.
2) This is not our fault, but... the single quote `'` in `Can't continue` is breaking the syntax highlighting in both Vim and Emacs :( Can we change the message for `Cannot continue`? (unless you have a better idea)

**Comment by SpotlightKid** [comment]
> The build fails when the current path contains spaces

Oh, I didn't now that make doesn't handle that. I'll read up on the syntax rules for `include` and rules in the documentation.

> Can we change the message for Cannot continue?

Sure, I first had just "Aborted." in there. But make always appends a dot and "Stop." (or "Schluss." in German) to `error` messages.

**Comment by SpotlightKid** [comment]
Unfortunately, I had to come to the conclusion that make does not work with paths containing spaces at all, so all paths referring to sub-makefiles need to be relative. This doesn't work with the way the makefiles in DPF refer to each other across sub and parent directories.

So I have to abandon the idea of making the DPF path configurable.

I'll close this PR and make a new one just for the `submodule` target issue.

**Pull request closed without merging**
