### PR TITLE
Add cairo template

### LINKED ISSUE #4: Add support for cairo-based UI
See: https://github.com/SpotlightKid/cookiecutter-dpf-effect/pull/2/files#r308602806

### PR DESCRIPTION
**Pull request by pdesaulniers**
This PR adds a cairo ui_type, as requested by @jpcima. Fixes https://github.com/SpotlightKid/cookiecutter-dpf-effect/issues/4

### CODE REVIEW

**Comment by SpotlightKid** [comment]
LGTM

**Comment by jpcima** [comment]
Thanks @pdesaulniers and @SpotlightKid

I have noted the template does not support generating a synth, which has a different prototype for the function `run`. I can try to add this when I study how the template system works.

**Comment by SpotlightKid** [comment]
I'd rather have different cookiecutter templates for different plugin types. I plan to do one for MIDI filters myself.

I'm also investigating switching from cookiecutter to [mr.bob](https://mrbob.readthedocs.io/en/latest/), because it allows for more dynamic templates, but that's still early days.

**Comment by pdesaulniers** [comment]
I'm not sure if making a different template altogether for synths is worth it. For generating a synth plugin, I think we just need to set a #define to 1 and tweak the `run` function. The rest would be duplicate code.

**Comment by SpotlightKid** [comment]
@pdesaulniers I'm open to discuss a PR.

**Pull request merged**
